engines:
  rubocop:
    enabled: true
  reek:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
  markdownlint:
    enabled: true
  git-legal:
    enabled: true
  flog:
      enabled: true

ratings:
   paths:
   - Gemfile.lock
   - "**.rb"
   - "**.md"

exclude_paths:
- "spec/app/**/*"
