# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_config}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jacques Crocker"]
  s.date = %q{2010-08-11}
  s.description = %q{Provides an easy to use Application Configuration object}
  s.email = %q{railsjedi@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README",
     "TODO"
  ]
  s.files = [
    "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README",
     "Rakefile",
     "TODO",
     "VERSION",
     "lib/generators/rails_config_generator.rb",
     "lib/generators/templates/rails_config.rb",
     "lib/rails_config.rb",
     "lib/rails_config/railtie.rb",
     "lib/rails_config/vendor/deep_merge.rb",
     "spec/fixtures/bool_override/config1.yml",
     "spec/fixtures/bool_override/config2.yml",
     "spec/fixtures/deep_merge/config1.yml",
     "spec/fixtures/deep_merge/config2.yml",
     "spec/fixtures/deep_merge2/config1.yml",
     "spec/fixtures/deep_merge2/config2.yml",
     "spec/fixtures/development.yml",
     "spec/fixtures/empty1.yml",
     "spec/fixtures/empty2.yml",
     "spec/fixtures/settings.yml",
     "spec/fixtures/settings2.yml",
     "spec/fixtures/with_erb.yml",
     "spec/rails_config_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/railsjedi/rails_config}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{provides an Settings for rails3 that reads config/settings.yml}
  s.test_files = [
    "spec/rails_config_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.19"])
  end
end

